### PR TITLE
Introduce Travis CI

### LINKED ISSUE #14: Add continuous integration
One candidate: TravisCI

### PR DESCRIPTION
**Pull request by zhengqunkoo**
Fix #14. All that's left to do is for @hipsleek to activate Travis CI on this repo.

Notes:
1. CI runs on Ubuntu 14.04, with dependencies from [hipsleek/dependencies](https://github.com/hipsleek/dependencies).
1. Environment variables `HIPSLEEK_TESTS_START` and `HIPSLEEK_TESTS_END` are assumed to be integers.
1. Tests are done by `diff`ing output from a run, to reference file in `/.travis`.
1. Second-last to fourth-last lines of output by `run-fast-tests.pl` and  `run-medium-tests.pl` are assumed to be timing information, unrelated to tests. Timing information must be ignored because they differ between runs.

### CODE REVIEW

**Comment by zhengqunkoo** [comment]
Some jobs still fail.

**Comment by hipsleek** [comment]
This is a work in progress by Zhengqun to set up CI using Travis.

**Comment by zhengqunkoo** [comment]
I believe I forgot to add `/usr/local/etc` to `PATH`.

**Comment by zhengqunkoo** [comment]
Gentle reminder: some Travis CI builds are nondeterministic. It is possible that restarting a failed build or restarting a failed job causes it to pass.

**Pull request merged**
